### ISSUE TITLE
How to start with image processing...

### ISSUE THREAD

**Issue by malvela** [sea-state-estimation/sea-state-estimation#5]
https://keras.io/examples/
https://docs.opencv.org/4.x/d2/d96/tutorial_py_table_of_contents_imgproc.html
https://www.tensorflow.org/tutorials/load_data/images
https://www.tensorflow.org/tensorboard/get_started
https://scikit-learn.org/stable/index.html
https://scikit-learn.org/stable/auto_examples/index.html

**Comment by rueskampn** [comment]
@cluedeke last 2 links (scikit) in my opinion also interesting for you
