### ISSUE TITLE
Set up BIBA Server

### ISSUE THREAD

**Issue by rueskampn** [sea-state-estimation/sea-state-estimation#7]
Struggeling with connecting to Biba-Server, dont see where to put public ssh-key for registration.

**Comment by malvela** [comment]
May u pls forward the email of our IT to me? I dont know exactly what he wants u to do... 
Probably u refer to the below links: 

https://www.simplified.guide/putty/public-key-authentication#:~:text=Public%20Key%20Authentication%20is%20one%20of%20the%20methods,SSH%20server%20using%20the%20public%20key%20authentication%20method.

https://www.ssh.com/academy/ssh/public-key-authentication#:~:text=The%20following%20simple%20steps%20are%20required%20to%20set,can%20prove%20they%20have%20the%20corresponding%20private%20key.

**Comment by rueskampn** [comment]
I sent an email to you with the requested emails.

edit:
Regarding link no. 1 our problem lies in Step 2: "Copy your public key to server's authorized_keys file. ", as we dont know how to access the server

**Comment by malvela** [comment]
does the vpn work for u? then pls launch terminal and write **ssh benutzer@rechner** (2.email)
